---
- hosts: web_servers
  become: true
  vars:
    ansible_user: ubuntu
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: Print OS info
      ansible.builtin.package:
        name: apache2
